name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Build and run tests
        run: |
          mkdir -p build
          cd build
          cmake ../ -DBUILD_PLUGIN_NOOP=ON -DENABLE_TESTS=ON
          make
          export VACCEL_BACKENDS=./plugins/noop/libvaccel-noop.so
          ./tests > ../test_output.txt
          ./test_plugins >> ../test_output.txt
          ./test_session >> ../test_output.txt
          ./test_misc >> ../test_output.txt
          ./test_resource >> ../test_output.txt
          ./test_id_pool >> ../test_output.txt
          ./test_fpga >> ../test_output.txt

      # - name: Remove headers and color codes from test output
      #   run: |
      #       sed -i 's/\x1b\[[0-9;]*m//g' $GITHUB_WORKSPACE/test_output.txt

      
      - name: Copy test output to README
        run: |
            echo '```' > temp_output.txt
            cat test_output.txt >> temp_output.txt
            echo '```' >> temp_output.txt
            mv temp_output.txt README.md
        shell: bash
      
      - uses: stefanzweifel/git-auto-commit-action@v4