name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Build and run tests
        run: |
          mkdir -p build
          cd build
          cmake ../ -DBUILD_PLUGIN_NOOP=ON -DENABLE_TESTS=ON -DBUILD_EXAMPLES=ON
          make
          ./tests > ../test_output.txt
          ./test_plugins >> ../test_output.txt
          ./test_session >> ../test_output.txt
          ./test_misc >> ../test_output.txt

      - name: Remove headers and color codes from test output
        run: |
          sed -i -e '/====/d' -e '/Randomness seeded to/d' -e 's/\x1b\[[0-9;]*m//g' ../test_output.txt
      
      - uses: stefanzweifel/git-auto-commit-action@v4